### ISSUE TITLE
Invalid docker container name when running make run

### ISSUE THREAD

**Issue by 89023890234890** [ValtteriL/OnionFermenter#2] opened 2023-08-02 14:37 UTC
```
$ sudo make run
Unable to find image 'valtteri/onionfermenter:latest' locally
latest: Pulling from valtteri/onionfermenter
91d30c5bc195: Pull complete 
1cfd666f9328: Pull complete 
44d0cbfa6a12: Pull complete 
4f4fb700ef54: Pull complete 
4c99dfa1ca21: Pull complete 
06be017e8228: Pull complete 
212c8432f503: Pull complete 
eae5a11d016c: Pull complete 
Digest: sha256:6df1cecea86fc96c31eee0519217f4c140fbbd47ab149a934c929dfd03055163
Status: Downloaded newer image for valtteri/onionfermenter:latest
docker: Error response from daemon: Invalid container name (-18769), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
See 'docker run --help'.
make: *** [Makefile:13: run] Error 125
```

I tried changing the $RANDOM variable in the Makefile to a non random value like "123123" but it spits the same error as in the error log above.

**Comment by 89023890234890** [comment] 2023-08-02 14:58
Also got this error before that one but fixed it by changing "--name" to "-v" in the Makefile:

$ make run
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'bitcoin-addresses.txt' mount path must be absolute.
See 'docker run --help'.
make: *** [Makefile:13: run] Error 125

**Comment by 89023890234890** [comment] 2023-08-02 15:04
I ment that I changed the "--mount" to "-v". I got it working somehow but theres nothing running? Also the get-addresses-docker doesn't seem to work:

```
$ make run
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'bitcoin-addresses.txt' mount path must be absolute.
See 'docker run --help'.
make: *** [Makefile:13: run] Error 125
$ nano Makefile 
$ make run
0ac50f78370b02d233aede42041af15d2f084a8a574c13518b83eec45cd4ad5f
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ make get-addresses-docker
```

**Comment by 89023890234890** [comment] 2023-08-02 15:21
After restarting docker.socket it no longer runs with the same invalid container name error:

```
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ sudo systemctl restart docker.socket 
$ docker ps
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
$ sudo systemctl restart docker.socket 
$ docker ps
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
$ make run
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd-28005": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
make: *** [Makefile:13: run] Error 126
$ sudo make run
docker: Error response from daemon: Invalid container name (-23706), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
See 'docker run --help'.
make: *** [Makefile:13: run] Error 125
$
```

**Comment by ValtteriL** [comment] 2023-08-02 17:20
What are the values for environment variables VICTIM_ONION_ID and ADDRESS_FILE?

Looking at your error messages I suspect the following:
1. You may have the '.onion' suffix on your VICTIM_ONION_ID. It should not be there.
2. Your ADDRESS_FILE seems to contain relative path to file "bitcoin-addresses.txt". It should be absolute path.

Please try again after checking these. @89023890234890

**Comment by 89023890234890** [comment] 2023-08-02 18:42
Removing the "-" from the "--name" in the Makefile on line 17 seems to get rid of the invalid container name error but it still doesn't launch the docker processes at all:

```
$ sudo make run
0c1dcd5539ce364ba824a462d860f22e16c96caa9139c33227a4982bbf4a96dd
$ sudo docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```
The make get-addresses also still does nothing, most likely because there is no Docker process running.

**Comment by ValtteriL** [comment] 2023-08-02 19:04
Your variables look correct.

I see you use sudo for the make command. The variables may not propagate to the privileged session.

Can you try either
`sudo -E make run`
or doing it all in privileged session, starting from the exports

**Comment by 89023890234890** [comment] 2023-08-02 19:17
Same result with `sudo -E make run` and redoing everything as a root user. The `make run` runs fine but no docker process starts. Below you can see the output from doing` docker ps -a`. Seems like it exits with an error?
```
# docker ps -a
CONTAINER ID   IMAGE                     COMMAND      CREATED          STATUS                      PORTS     NAMES
cb51d6ba708e   valtteri/onionfermenter   "./run.sh"   38 minutes ago   Exited (1) 38 minutes ago             sharp_almeida
```

**Comment by ValtteriL** [comment] 2023-08-02 19:24
Just to confirm: Did you undo all changes you did to the code, especially Makefile?

**Comment by 89023890234890** [comment] 2023-08-02 19:41
Yes. Default Makefile.

**Comment by ValtteriL** [comment] 2023-08-02 21:11
I was able to reproduce the issue. It was caused by the VOLUME statement it the Dockerfile, which broke only docker deployment.

I fixed the issue and built a new container with tag '2-fix-permission-issue'. I shall test k8s deployment before merging to main and replacing the latest container image.

Meanwhile you may plug that tag into the make run command and see what happens.

**Comment by 89023890234890** [comment] 2023-08-03 12:53
```
# make run 2-fix-permission-issue
ea07e37f5d45cec77447aecb4d3108a9f35a7c50de8f4cb6eecdb62f70a38a18
make: *** No rule to make target '2-fix-permission-issue'.  Stop.
```

**Comment by ValtteriL** [comment] 2023-08-03 18:36
The fix is now merged to main. Please use the latest code and try again. You may need to delete old docker image to ensure the fixed one is pulled.

You can delete the old image with command `docker rmi valtteri/onionfermenter:latest`

Please let me know if you still face problems. I will otherwise close this issue in 24 hours.

@89023890234890

**Comment by 89023890234890** [comment] 2023-08-03 19:23
Seems to build fine now but the get-addresses-docker command doesn't work.

```
$sudo docker ps
CONTAINER ID   IMAGE                            COMMAND      CREATED         STATUS         PORTS     NAMES
ada90a4230f7   valtteri/onionfermenter:latest   "./run.sh"   9 seconds ago   Up 7 seconds             26983
$sudo make get-addresses-docker
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```

**Comment by ValtteriL** [comment] 2023-08-04 04:44
The get-addresses and get-addresses-docker rely on the VICTIM_ONION_ID environment variable.

Thus if you use sudo here as well, you need to provide the same -E flag as with `sudo -E make run`. So it becomes `sudo -E get-addresses-docker`.

The hidden_service directory is inside the container.

**Comment by 89023890234890** [comment] 2023-08-04 11:19
I got the .onion address but when I visit it in Tor browser I get this:

`The requested onion service descriptor can't be found on the hashring and therefore the service is not reachable by the client.`

**Comment by ValtteriL** [comment] 2023-08-04 12:39
It takes around 5 minutes for onion services to be publicly reachable after starting.

Please let it run for a while and try accessing it again.

**Comment by ValtteriL** [comment] 2023-08-04 17:03
OnionFermenter intercepts everything but just does not do anything with the data, except for modifying onion and bitcoin addresses and relaying it.

I guess you would like to have it print out any credentials in the intercept. It is hard to have general solution printing just credentials that works with any onion services. It is though possible and easy to just log all traffic and then manually search it for credentials.

In fact the functionality to save all traffic from clients to file is currently only commented out: https://github.com/ValtteriL/OnionFermenter/blob/5a2b770f5d8ce695cdc7c5c2864334d2da05a136/src/onionfermenter_worker_server.erl#L66

**Comment by ValtteriL** [comment] 2023-08-04 17:04
Fixed in https://github.com/ValtteriL/OnionFermenter/pull/3

**Closed by ValtteriL** 2023-08-04 17:04 UTC
